---
- name:  Just a little bit on loops
  hosts: localhost
  gather_facts: no

  vars:
          myList:
                  - "A hyphen is an entry in a list"
                  - "Thise would be the second item on the list"
                  - "Number 3"

  tasks:
         - name: Demo my little loop
           debug:
                   msg: "The debug mod allows us to display to the screen: {{ item }}"
           loop: "{{ myList }}"

         - name: Demo a second tiny loop
           debug:
                   msg: "All mods can also have LOCAL var information: {{ item }}"
           loop: "{{ myOtherList }}"
           vars:
                   myOtherList:
                           - example of local info
                           - only available to this task
