---
- name: push a script to a host and run it
  hosts: futurama

  gather_facts: yes

  tasks:
          - name: run python script
            script: /home/student/ans/py/holamundo.py
            args:
                    executable: python3
            register: results

          - name:  what did holamundo produce
            debug:
                    var: results
